version: '3.9'

services:
  web:
    build:
      context: .
    command: pnpm start
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ${PWD}/web/:/src
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - api
  api:
    build:
      context: .
    command: pnpm start:server
    ports:
      - 3001:3001
    working_dir: /src
    volumes:
      - ${PWD}/web/:/src
    